GET http://localhost:3005/api/person

###
GET http://localhost:3005/api/user


###
GET http://localhost:3005/api/person/67aa21c50e8e631dbf097fd4

###
GET http://localhost:3005/api/person/dni/45678901E