GET http://localhost:3005/api/person

###
GET http://localhost:3005/api/user


###
GET http://localhost:3005/api/person/45678901E

###
GET http://localhost:3005/api/person/filtered?tipoUsuario=alumno

###
GET http://localhost:3005/api/person/filtered?tipoUsuario=alumno&curso=3º&modalidad=Presencial&tipoTitulacion=Grado
